### ISSUE TITLE
Issue 7 for karma 

### ISSUE THREAD

**Issue by aahana11234** [KarmaSherpaa/Tms#17]
![karma](https://user-images.githubusercontent.com/128129304/228867550-0e38af58-a7c4-4273-b99a-fa37c54a6095.png)
There is no link sent to the user to change the password.

**Comment by KarmaSherpaa** [comment]
Solved
![image](https://user-images.githubusercontent.com/126855790/229306004-ef33f39f-c689-4adb-9a7d-d70c46bcc791.png)
