### ISSUE TITLE
Isssue 8 for karma 

### ISSUE THREAD

**Issue by aahana11234** [KarmaSherpaa/Tms#18]
![karma2](https://user-images.githubusercontent.com/128129304/228868451-bde09917-8ed5-4886-913e-6f19c75d5b9c.png)
The data is not being updated.

**Comment by KarmaSherpaa** [comment]
issue solved 
![image](https://user-images.githubusercontent.com/126855790/229305750-5804419d-eda0-49f8-a498-15dbde6f1c57.png)

**Comment by KarmaSherpaa** [comment]
The data will be deleted and updated through profile
